# Generated by Django 2.1.4 on 2019-01-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
