# Generated by Django 2.1.4 on 2019-01-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publ_date',
            field=models.DateField(),
        ),
    ]
